### ISSUE TITLE
Snake game with python

### ISSUE THREAD

**Issue by Naman-pokhriyal** [Naman-pokhriyal/HacktoberFest#1]
Create a file in Python folder
No need to ask for assignment. Just get coding.

Happy Coding!!
All the Best

**Comment by DelayCoderz** [comment]
I've done a pull request for this issue, please see the results this my first Pull Request In HacktoberFest 2021 Event :)

**Comment by Naman-pokhriyal** [comment]
Done 2021

**Comment by Naman-pokhriyal** [comment]
Done 2021
